# Library documentation: http://tactician.thephpleague.com/
# Bundle documentation: https://github.com/thephpleague/tactician-bundle/blob/v1.0/README.md
tactician:
    commandbus:
        default:
            middleware:
# Locking middleware - http://tactician.thephpleague.com/plugins/locking-middleware/
#                - tactician.middleware.locking
# Doctrine transactional middleware, requires additional package - https://github.com/thephpleague/tactician-doctrine
                - tactician.middleware.doctrine
                - tactician.middleware.command_handler

        noflush:
            middleware:
                - tactician.middleware.command_handler