parameters:
    repository_type: doctrine

services:

    # DOMAIN
    domain_repository:
        alias: domain_repository.doctrine
        public: true

    domain_repository.dbal:
        class: App\Infrastructure\Repository\DBAL\DbalDomainRepository
        arguments: ["@database_connection"]
        public: false

    domain_repository.doctrine:
        class: App\Infrastructure\Repository\Doctrine\DoctrineDomainRepository
        arguments: ["@doctrine.orm.entity_manager"]
        public: false

    # GROUP
